# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrella',
            name='State',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='control.State'),
            preserve_default=False,
        ),
    ]
