# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20171008_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrella',
            name='IP',
            field=models.CharField(max_length=255),
        ),
    ]
