# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20171008_0656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Umbrella',
            new_name='Playera',
        ),
    ]
