# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20171008_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playera',
            old_name='IP',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='playera',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='playera',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='Name',
            new_name='name',
        ),
    ]
