# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20180701_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playera',
            name='state',
            field=models.BooleanField(max_length=255),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
